<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerItZBqxr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerItZBqxr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerItZBqxr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerItZBqxr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerItZBqxr\App_KernelDevDebugContainer([
    'container.build_hash' => 'ItZBqxr',
    'container.build_id' => 'b90aaa74',
    'container.build_time' => 1654100998,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerItZBqxr');
