<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRlCc0aF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRlCc0aF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRlCc0aF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRlCc0aF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRlCc0aF\App_KernelDevDebugContainer([
    'container.build_hash' => 'RlCc0aF',
    'container.build_id' => '6153eeb1',
    'container.build_time' => 1654090164,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRlCc0aF');
